definitions:
  DTO.ProductDTO:
    properties:
      category:
        type: string
      id:
        type: string
      price:
        type: number
      quantity:
        type: integer
      ratting:
        type: number
      reviewsCount:
        type: integer
      salesMan:
        type: string
    type: object
  ErrorMessage:
    properties:
      message:
        type: string
    type: object
  Response:
    properties:
      data: {}
      error:
        $ref: '#/definitions/ErrorMessage'
      message:
        type: string
    type: object
  api.CreateProductRequest:
    properties:
      productDTO:
        $ref: '#/definitions/DTO.ProductDTO'
    type: object
  entities.Error:
    properties:
      message:
        example: Unknown error
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/{id}/rate:
    get:
      description: GetSeveralProducts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/Response'
            - properties:
                error:
                  $ref: '#/definitions/entities.Error'
              type: object
      summary: GetSeveralProducts
      tags:
      - Product
  /api/v1/products:
    post:
      consumes:
      - application/json
      description: Creates new product
      parameters:
      - description: Create product request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.CreateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/Response'
            - properties:
                error:
                  $ref: '#/definitions/entities.Error'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/Response'
            - properties:
                error:
                  $ref: '#/definitions/entities.Error'
              type: object
      summary: Creates new product
      tags:
      - Product
  /api/v1/products/{id}:
    post:
      consumes:
      - application/json
      description: Deletes product
      parameters:
      - description: Create product request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.CreateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/Response'
            - properties:
                error:
                  $ref: '#/definitions/entities.Error'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/Response'
            - properties:
                error:
                  $ref: '#/definitions/entities.Error'
              type: object
      summary: Deletes product
      tags:
      - Product
  /api/v1/products/{id}/order:
    post:
      description: Order products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/Response'
            - properties:
                error:
                  $ref: '#/definitions/entities.Error'
              type: object
      summary: Order products
      tags:
      - Product
swagger: "2.0"
