server:
  host: 0.0.0.0
  port: 8082

swagger:
  enabled: true
  endpoint: /swagger

metrics:
  enabled: true
  endpoint: /metrics
  export_default: true

health:
  enabled: true
  endpoint: /healthz

integrations:
  keycloak:
    # uri: http://keycloak:8080
    # uri: http://127.0.0.1:18080
    uri: "https://keycloak.teneshag.ru"
    client:
      id: test-auth
      # secret: S4KpMZDp1vvJQyiB7BsfaFkhFKdgzrgC
      secret: GN3hOiAkSiZAmTLCtAlDiN5is5KjsQOc
    admin:
      username: admin123
      # password: admin
      password: d04c85ed-5254-4b2d-99dc-dc6d43af7312
      realm: master
    token_refresh_interval: 30
    realm: test
