gateapp: &gateconf
  server:
    host: 0.0.0.0
    port: 8082

  swagger:
    enabled: true
    endpoint: /swagger

  metrics:
    enabled: true
    endpoint: /metrics
    export_default: true

  health:
    enabled: true
    endpoint: /healthz

  integrations:
    keycloak:
      # uri: http://keycloak:8080
      uri: http://keycloak.teneshag.ru
      client:
        id: test-auth
        secret: GN3hOiAkSiZAmTLCtAlDiN5is5KjsQOc
      admin:
        username: admin123
        password: d04c85ed-5254-4b2d-99dc-dc6d43af7312
        realm: master
      token_refresh_interval: 30
      realm: test
    rabbitmq:
#      dsn: amqp://rabbitmqadmin:rabbitmqadmin@rabbitmq:5672
#      dsn: amqp://rabbitmqadmin:rabbitmqadmin@rabbitmq:5672
      dsn: amqp://rabbitmqadmin:rabbitmqadmin@rabbitmq:5672 #for local debbuging, no docker!
      exchange: crud
      max_retries: 1
    postgres:
      host: catalog_db
      port: 5432
      password: qqqwwweee12321
      user: postgres
      dbname: postgres

coreapp:
  <<: *gateconf
  server:
    host: 0.0.0.0
    port: 8083
  swagger:
    enabled: false

